// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHNlHAB_bYA1-P5IB9BnSYrcfVZZlsKIE',
    appId: '1:447455254557:web:5f3a735958b35dbba68ef4',
    messagingSenderId: '447455254557',
    projectId: 'siyasatph',
    authDomain: 'siyasatph.firebaseapp.com',
    storageBucket: 'siyasatph.firebasestorage.app',
    measurementId: 'G-HW0L0W6TWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESWMc5vQz4APfPFMp551oyghVGAvZHJo',
    appId: '1:447455254557:android:939836e4fd1e7774a68ef4',
    messagingSenderId: '447455254557',
    projectId: 'siyasatph',
    storageBucket: 'siyasatph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-eNAqyGbdLD72kMQRMtrK87vklYEDXkM',
    appId: '1:447455254557:ios:c6b633bc78deb241a68ef4',
    messagingSenderId: '447455254557',
    projectId: 'siyasatph',
    storageBucket: 'siyasatph.firebasestorage.app',
    iosBundleId: 'com.example.siyasatPh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-eNAqyGbdLD72kMQRMtrK87vklYEDXkM',
    appId: '1:447455254557:ios:c6b633bc78deb241a68ef4',
    messagingSenderId: '447455254557',
    projectId: 'siyasatph',
    storageBucket: 'siyasatph.firebasestorage.app',
    iosBundleId: 'com.example.siyasatPh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHNlHAB_bYA1-P5IB9BnSYrcfVZZlsKIE',
    appId: '1:447455254557:web:fabbf38d693152b3a68ef4',
    messagingSenderId: '447455254557',
    projectId: 'siyasatph',
    authDomain: 'siyasatph.firebaseapp.com',
    storageBucket: 'siyasatph.firebasestorage.app',
    measurementId: 'G-ZWQ2JBD81E',
  );
}
